---
- name: configouring apache server
  hosts: web01
  become: yes  
  tasks: 
    - name: Install apache2 package  
      apt:
        name: apache2
        state: present 
        update_cache: yes  
    - name: Start apache server
      service:
        name: apache2
        state: started   
    - name: Add ufw firewall rules
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp  
    - name: Reload ufw firewall  the new rule
      community.general.ufw:
        state: enabled
    - name: Copy index file to apache directory
      copy:
        src: /tmp/index.html
        dest: /var/www/html
        mode: '0644'  
    - name: Restart apache service
      service:
        name: apache2
        state: restarted
...          

